config/routes.rb
TestJob::Application.routes.draw do
  resources :orders

  resources :line_items
  resources :carts

  root 'products#index'
  post 'user/add_balance'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  include TotalPrice

  has_many :line_items, dependent: :destroy
  belongs_to :user

  validate :validate_line_items, :validate_user_balance


  scope :all_include, -> { includes(:user, line_items: :product) }
  scope :order_by_create, -> { order(created_at: :desc) }


  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def save_with_transaction
    if valid?
      User.transaction do
        fail 'Your cart empty' if line_items_empty?
        fail 'Need more gold!' unless enough_user_balance?
        user.increment!(:balance, - total_price)
        save! validate: false
      end
    end
  end

  private

  def validate_line_items
    if line_items_empty?
      errors.add(:line_items, 'Line items cant be empty')
    end
  end

  def validate_user_balance
    unless enough_user_balance?
      errors.add(:user, 'Have not enough money, please top up an account')
    end
  end

  def line_items_empty?
    line_items.empty?
  end

  def enough_user_balance?
    if user
      total_price < user.reload.balance
    else
      false
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < AuthController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all_include.order_by_create.page(params[:page]).per(10)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end


  # POST /orders
  # POST /orders.json
  def create
    @cart = current_cart

    if @cart.line_items.empty?
      redirect_to root_path, notice: 'Empty cart'
      return
    end

    @order = Order.new
    @order.user = current_user
    @order.add_line_items_from_cart(current_cart)

    respond_to do |format|
      notice = []
      begin
        saved = @order.save_with_transaction
      rescue Exception => e
        notice = [e.message] || ['Error with order saving.']
      end
      if saved
        session[:cart_id] = nil
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        notice = @order.errors.to_a unless @order.errors.empty?
        format.html { redirect_to @cart, notice: notice.join('.') }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit()
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions = f.submit 'Save'

app/views/orders/_line_items.html.slim
- line_items.each do |item|
  | #{item.quantity} x #{item.product.title} <br>

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table
  tr
    th Id
    th Date
    th Email
    th Products
    th Total price

  - @orders.each do |order|
    tr
      td = order.id
      td = order.created_at
      td = order.user.email
      td = render partial: "line_items", locals: {line_items: order.line_items}
      td.item_price = number_to_currency(order.total_price)

br

p = paginate @orders

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
p#notice = notice

p
  strong User:
  = @order.user_id

= link_to 'Edit', edit_order_path(@order)
'|
= link_to 'Back', orders_path