config/routes.rb
TestJob::Application.routes.draw do
  resources :orders

  resources :line_items
  resources :carts

  root 'products#index'
  post 'user/add_balance'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy

  accepts_nested_attributes_for :line_items

  include TotalPrice

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < AuthController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts/1
  # GET /carts/1.json
  def show
    if @cart.line_items.empty?
      redirect_to root_path, notice: 'Empty cart'
      return
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      saved = @cart.update_attributes(cart_params)
      @cart.line_items.select{ |item| item.quantity <= 0 }.map(&:destroy)
      if saved
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @cart, notice: 'Cart wasn\'t updated.' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      begin
        @cart = current_cart
        if @cart.id != params[:id].to_i
          redirect_to root_url, notice: 'Not yours Cart'
        end
      rescue ActiveRecord::RecordNotFound
        redirect_to root_url, notice: 'Unexisting Cart'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(line_items_attributes: [:quantity, :product_id, :id])
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
'|
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  tr
    th
    th
    th

  - @carts.each do |cart|
    tr
      td = link_to 'Show', cart
      td = link_to 'Edit', edit_cart_path(cart)
      td = link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
== form_for @cart, method: :patch do |cart_form|
  table.table
    tr
      th = Cart.human_attribute_name(:quantity)
      th = Cart.human_attribute_name(:title)
      th = Cart.human_attribute_name(:price)
    = cart_form.fields_for :line_items do |item_form|
      tr
        td.item_count
          = item_form.text_field :quantity, type: 'number'
          = item_form.hidden_field :product_id
        td = item_form.object.product.title
        td.item_price = number_to_currency(item_form.object.total_price)
        td = link_to 'Delete', line_item_path(item_form.object), method: :delete
    tr
      td colspan=2 Total
      td.item_price = number_to_currency(@cart.total_price)
  div.buttons
    == cart_form.submit 'Update'

== button_to 'Checkout', orders_path, method: :post, class: 'checkout_button'
== button_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?'