config/routes.rb
TestJob::Application.routes.draw do
  resources :orders

  resources :line_items
  resources :carts

  root 'products#index'
  post 'user/add_balance'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < AuthController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]


  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find params[:product_id]
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart}
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = @line_item.cart
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @cart }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.slim
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      ul
        - @line_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .field
    = f.label :product_id
    = f.number_field :product_id
  .actions = f.submit 'Save'

app/views/line_items/edit.html.slim
h1 Editing line_item

== render 'form'

= link_to 'Show', @line_item
'|
= link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line_items

table
  tr
    th Cart
    th Product
    th
    th
    th

  - @line_items.each do |line_item|
    tr
      td = line_item.cart_id
      td = line_item.product_id
      td = link_to 'Show', line_item
      td = link_to 'Edit', edit_line_item_path(line_item)
      td = link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line_item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong Cart:
  = @line_item.cart_id
p
  strong Product:
  = @line_item.product_id

= link_to 'Edit', edit_line_item_path(@line_item)
'|
= link_to 'Back', line_items_path